### ISSUE TITLE
sound header error

### ISSUE THREAD

**Issue by benqbenqbenq** [Arnuh/HaSuite#26]
----- Start of the error log. [2024-03-05 AM 12:00:00] -----
[Critical] : parse sound header failed

in errors.txt

**Comment by benqbenqbenq** [comment]
Also, i can't enter the map even if erase only one object

**Comment by benqbenqbenq** [comment]
If you can resolve it, I can pay some money... plz

**Comment by Arnuh** [comment]
provide wz

**Comment by Arnuh** [comment]
Your minimap has "listWz: True" but I don't see any List.wz in either of those versions. This could cause crashes as the client is unable to decrypt the image.

I've released https://github.com/Arnuh/HaSuite/releases/tag/v2.0-beta.1 which handles List.wz better, you're also able to strip remove the List.wz encryption with Right Click > Etc > "Check List.wz entries"

**Comment by benqbenqbenq** [comment]
> Your minimap has "listWz: True" but I don't see any List.wz in either of those versions. This will cause crashes as the client is unable to decrypt the image.
> 
> I've released https://github.com/Arnuh/HaSuite/releases/tag/v2.0-beta.1 which handles List.wz better, you're also able to remove the List.wz encryption with Right Click > Etc > "Check List.wz entries"

**Should I use the list.wz function before I modify it to a PheCreator?**

**Comment by Arnuh** [comment]
hard to tell what is going on because proper support for Data directory doesn't exist on this tool yet and you could have done dozens of things I don't know about to cause issues
