### ISSUE TITLE
Exception Thrown when trying to repack using other map assets.

### ISSUE THREAD

**Issue by Masterrulax** [Arnuh/HaSuite#27]
Saving works fine, the issue happens when trying to repack.

The issue: Placing any background in a map from the backgrounds selection and then trying to save and repack will throw an exception:

![image](https://github.com/Arnuh/HaSuite/assets/44963525/97523441-d002-4958-ae0d-4e7a1f5aeaf0)

You press OK and then this pop up appears:

![image](https://github.com/Arnuh/HaSuite/assets/44963525/693f8188-7d58-4c1a-9d1d-191e0e77d9da)

I tested with objects and tiles and had no issue repacking, seems to be only happening with backgrounds.

PSA: Tested this with my WZ files and with clean WZ files, same issue.

**Comment by Arnuh** [comment]
[HaSuite-x64-2.0.8834.zip](https://github.com/Arnuh/HaSuite/files/14548354/HaSuite-x64-2.0.8834.zip)

**Comment by Masterrulax** [comment]
Issue seems to be resolved!

I will make another issue post if anything else appears!

Thanks a bunch man
