### ISSUE TITLE
Invisible walls are created when modifying maps using creator

### ISSUE THREAD

**Issue by PaperChonChon** [Arnuh/HaSuite#43]
i noticed when using your creator, loading map 100000200 (Henesys Park), in my v83 version, on the left there is a bridge, i would get stuck when walking around if i exported the map using your tool. in the original map that i loaded into creator, it does not have this issue
![GIF 23-4-2024 22-34-27](https://github.com/Arnuh/HaSuite/assets/40238280/bc1318cb-2f9a-45f9-b661-a2e9dfc6619a)
![image](https://github.com/Arnuh/HaSuite/assets/40238280/485e3fdb-bed5-46c6-ac88-54c416de0c3b)

**Comment by Arnuh** [comment]
Should just be exactly the same as #39 so closing as dupe
