### ISSUE TITLE
Support directory selection when importing xml img

### ISSUE THREAD

**Issue by wangxiaobao0851** [Arnuh/HaSuite#49]
When importing .xml .img files, I hope that it can support selecting directories and automatically create directories. Currently, many people use IMG loader, and sometimes they hope to restore to .wz files, but this requires manually creating all directories. If it can support selecting directories, it will be very convenient.

**Comment by wangxiaobao0851** [comment]
Sorry, I just checked the update history. v2.0-beta.2 already supports importing directories. This issue will be closed.

**Comment by Arnuh** [comment]
Yeah the import folder option is the current best way to handle IMG for certain operations. Further support is in the future but requires a lot more work.
